config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'landing/index'
  root to: 'landing#index'

  match '/auth/:provider/callback',           to: 'sessions#create', via: [:get, :post]
  get   '/login',                             to: 'sessions#new'
  get   '/auth/failure',                      to: 'sessions#failure'
  match '/logout',                            to: 'sessions#destroy', via: [:get, :post]
  get   '/signup',                            to: 'identities#new' # registering user with omniauth-identity
  get   '/home',                              to: 'homes#index'
  post  '/contact/submit',                    to: 'forms#submit_contact'
  put   '/account/choose',                    to: 'accounts#choose'
  get   '/plans',                             to: 'application#plans_route'

  resources :accounts
  resources :identities
  resources :statements                     
  resources :users,                           only: [:show]
  resources :statement_files,                 only: [:index, :new, :create, :destroy]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount Sidekiq::Web, at: '/sidekiq' if Rails.env.development?
end
 

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  skip_before_action :check_subscription!, only: [:index]

  layout "landing"

  def index
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/_features-message-desktop.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <h1 class="mdl-typography--display-2">
      O que é?
    </h1>
    <p class="mdl-typography--body-1">
      Vivamus nec odio nec enim dictum consectetur a sit amet quam. Proin dictum est arcu, ut iaculis<br/>est vulputate ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec sagittis<br/>massa mollis metus sollicitudin, non venenatis est sodales.
    </p>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div class="features-img-container">
      <%= image_tag "Features-1.svg" %>
    </div>
    <h5>Lorem Ipsum dolor sit amet um</h5>
    <p>Sed cursus purus ac ligula hendrerit pharetra. Curabitur euismod, nulla vel porta porttitor, sem est malesuada quam, in pretium libero enim vestibulum risus.</p>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div class="features-img-container">
      <%= image_tag "Features-2.svg" %>
    </div>
    <h5>Lorem Ipsum dolor sit amet um</h5>
    <p>Sed cursus purus ac ligula hendrerit pharetra. Curabitur euismod, nulla vel porta porttitor, sem est malesuada quam, in pretium libero enim vestibulum risus.</p>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div class="features-img-container">
      <%= image_tag "Features-3.svg" %>
    </div>
    <h5>Lorem Ipsum dolor sit amet um</h5>
    <p>Sed cursus purus ac ligula hendrerit pharetra. Curabitur euismod, nulla vel porta porttitor, sem est malesuada quam, in pretium libero enim vestibulum risus.</p>
  </div>
</div>

app/views/landing/_features.html.erb
<div class="mdl-grid" id="features">
  <div class="mdl-cell mdl-cell--12-col">
    <h1 class="mdl-typography--display-2 section-title">
      O que é?
    </h1>
    <p class="mdl-typography--body-1">
      Vivamus nec odio nec enim dictum consectetur a sit amet quam. Proin dictum est arcu, ut iaculis<br/>est vulputate ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec sagittis<br/>massa mollis metus sollicitudin, non venenatis est sodales.
    </p>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div class="img-container">
      <%= image_tag "Features-1.svg" %>
    </div>
    <h5 class="landing-column-subtitle">Lorem Ipsum dolor sit amet um</h5>
    <p>Sed cursus purus ac ligula hendrerit pharetra. Curabitur euismod, nulla vel porta porttitor, sem est malesuada quam, in pretium libero enim vestibulum risus.</p>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div class="img-container">
      <%= image_tag "Features-2.svg" %>
    </div>
    <h5 class="landing-column-subtitle">Lorem Ipsum dolor sit amet um</h5>
    <p>Sed cursus purus ac ligula hendrerit pharetra. Curabitur euismod, nulla vel porta porttitor, sem est malesuada quam, in pretium libero enim vestibulum risus.</p>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div class="img-container">
      <%= image_tag "Features-3.svg" %>
    </div>
    <h5 class="landing-column-subtitle">Lorem Ipsum dolor sit amet um</h5>
    <p>Sed cursus purus ac ligula hendrerit pharetra. Curabitur euismod, nulla vel porta porttitor, sem est malesuada quam, in pretium libero enim vestibulum risus.</p>
  </div>
</div>

app/views/landing/_form.html.erb
<div class="mdl-grid" id="form-section">
  <div class="mdl-cell mdl-cell--4-col">
    <%= image_tag "ilustra-form.svg", { id: "form-illustration" } %>
  </div>
  <div class="mdl-cell mdl-cell--8-col mdl-cell--4-col-phone">
    <h1 class="mdl-typography--display-2">
      Tem alguma dúvida?<br />Entre em contato conosco
    </h1>
    <%= form_with scope: :contact, url: contact_submit_path, local: true do |f| %>
      <% flash.each do |type, msg| %> 
        <div class="#{type}">
        <span class="material-icons feedback-icon">warning</span><%= msg %>
        </div>
      <% end %>
      <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--12-col mdl-cell--4-col-phone landing-form-item">
          <div class="mdl-textfield mdl-js-textfield">
            <%= f.label 'Seu Email', class: "mdl-textfield__label" %>
            <%= f.text_field :email, class: "mdl-textfield__input" %>
          </div>
        </div>
        <div class="mdl-cell mdl-cell--12-col mdl-cell--4-col-phone landing-form-item">
          <div class="mdl-textfield mdl-js-textfield landing-form-multiline-field">
            <%= f.label 'Sua Mensagem', class: "mdl-textfield__label" %>
            <%= f.text_area :message, class: "mdl-textfield__input", rows: 5 %>
          </div>
        </div>
        <div class="mdl-cell mdl-cell--12-col mdl-cell--4-col-phone landing-form-item">
          <div class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent">
            enviar&nbsp;<span class="material-icons">send</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/landing/_header-desktop.html.erb
<header class="mdl-layout__header mdl-layout__header--transparent" id="landing-header">
  <div class="mdl-layout__header-row landing-nav-header-row">
    <span class="mdl-layout-title">
      <%= image_tag "logo.svg", { id: "landing-nav-logo" } %>
    </span>
    <div class="mdl-layout-spacer"></div>
    <nav class="mdl-navigation">
      <a href="#features">
        <div class="mdl-button mdl-js-button mdl-button--accent landing-header-item">
          o que é
        </div>
      </a>
      <a href="#price">
        <div class="mdl-button mdl-js-button mdl-button--accent landing-header-item">
          preço
        </div>
      </a>
      <a href="/login">
        <div id="landing-nav-login-button" class="mdl-button mdl-js-button mdl-button--accent landing-header-item">
          fazer login
        </div>
      </a>
      <a href="/signup">
        <div class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent landing-header-item">
          quero assinar
        </div>
      </a>
    </nav>
  </div>
</header>

app/views/landing/_header-phone.html.erb
<div class="mdl-layout__drawer">
  <div class="mdl-layout__title landing-drawer-logo-container">
    <%= image_tag "logo.svg", { id: "landing-nav-logo" } %>
  </div>
  <nav class="mdl-navigation">
    <a href="#features" class="landing-drawer-nav-child">
      <div class="mdl-button mdl-js-button mdl-button--accent landing-drawer-nav-button">
        o que é
      </div>
    </a>
    <a href="#price" class="landing-drawer-nav-child">
      <div class="mdl-button mdl-js-button mdl-button--accent landing-drawer-nav-button">
        preço
      </div>
    </a>
    <a href="/login" class="landing-drawer-nav-child">
      <div id="landing-nav-login-button" class="mdl-button mdl-js-button mdl-button--accent landing-drawer-nav-button">
        fazer login
      </div>
    </a>
    <a href="/signup" class="landing-drawer-nav-child">
      <div class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent landing-drawer-nav-button">
        quero me inscrever
      </div>
    </a>
  </nav>
</div>

app/views/landing/_hero-message-desktop.html.erb
<div class="mdl-cell mdl-cell--6-col" id="hero-message__desktop">
  <div id="hero-message-text">
    <span class="mdl-typography--display-2">
      A Optax ajuda<br/>você a controlar o<br/>resultado dos seus investimentos em bolsa
    </span>
  </div>
  <a href="#features">
    <div class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent" id="hero-button">
      saiba mais <span class="material-icons">arrow_downward</span>
    </div>
  </a>
</div>

app/views/landing/_hero-message-phone.html.erb
<div class="mdl-cell mdl-cell--4-col-phone" id="hero-message__phone">
  <span class="mdl-typography--display-1">
    A Optax ajuda você a controlar os resultados dos seus investimentos em Bolsa
  </span>
</div>

app/views/landing/_price-desktop.html.erb
<div class="mdl-grid" id="price__desktop">
  <div class="mdl-cell mdl-cell--12-col section-title">
    <span class="mdl-typography--display-2">
      Preço
    </span>
  </div>
  <div class="mdl-cell mdl-cell--6-col">
    <div class="feature-item">
      <p class="mdl-typography--headline">Funcionalidades inclusas:</p>
      <%= image_tag "price-icon-1.svg", { class: "price-icon" } %>
      <h5 class="mdl-typography--title feature-title">Geração de DARFs</h5>
      <p>
        Você acessa todas as guias de impostos sobre as vendas 
        dos seus ativos, com controle fácil do que falta pagar
      </p>
    </div>
    <div class="feature-item">
      <%= image_tag "price-icon-2.svg", { class: "price-icon" } %>
      <h5 class="mdl-typography--title feature-title">Relatórios para o imposto de renda</h5>
      <p>
        Em Abril, você ou seu contador vão copiar e colar apenas, com um layout espelho do IRPF
      </p>
    </div>
    <div class="feature-item">
      <%= image_tag "price-icon-3.svg", { class: "price-icon" } %>
      <h5 class="mdl-typography--title feature-title">Análises mensais</h5>
      <p>
        Desdobramentos, bonificações, grupamentos e proventos
      </p>
    </div>
  </div>
  <div class="mdl-cell mdl-cell--6-col" id="price-illustration-col">
    <div id="price-content-container">
      <%= image_tag "price-illustration.svg", { id: "price-illustration" } %>
      <div>
        <p>
          <span id="price-value">R$ 20,00</span>
          <span class="mdl-typography--title">/mês</span>
        </p>
        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent">
          crie sua conta
        </button>
      </div>
    </div>
  </div>
</div>

app/views/landing/_price.html.erb
<div class="mdl-grid" id="price">
  <div class="mdl-cell mdl-cell--12-col">
    <h1 class="mdl-typography--display-2 section-title">
      Preço
    </h1>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div>
      <div class="landing-price-container">
        <%= image_tag "price-illustration.svg", {class: "landing-price-img"} %>
      </div>
      <p class="price-text">R$ 20,00</p>
      <div class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent landing-price-button">
        crie sua conta
      </div>
    </div>
    <h5 class="landing-column-subtitle">Lorem Ipsum dolor sit amet um</h5>
    <p>Sed cursus purus ac ligula hendrerit pharetra. Curabitur euismod, nulla vel porta porttitor, sem est malesuada quam, in pretium libero enim vestibulum risus.</p>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div>
      <div class="landing-price-container">
        <%= image_tag "price-illustration-2.svg", {class: "landing-price-img"} %>
      </div>
      <p class="price-text">R$ 20,00</p>
      <div class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent landing-price-button">
        crie sua conta
      </div>
    </div>
    <h5 class="landing-column-subtitle">Lorem Ipsum dolor sit amet um</h5>
    <p>Sed cursus purus ac ligula hendrerit pharetra. Curabitur euismod, nulla vel porta porttitor, sem est malesuada quam, in pretium libero enim vestibulum risus.</p>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <div>
      <div class="landing-price-container">
        <%= image_tag "price-illustration-3.svg", {class: "landing-price-img"} %>
      </div>
      <div id="price-col3-spacer"></div>
      <div class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent landing-price-button">
        entre em contato
      </div>
    </div>
    <h5 class="landing-column-subtitle">Lorem Ipsum dolor sit amet um</h5>
    <p>Sed cursus purus ac ligula hendrerit pharetra. Curabitur euismod, nulla vel porta porttitor, sem est malesuada quam, in pretium libero enim vestibulum risus.</p>
  </div>
</div>

app/views/landing/index.html.erb
<%= render "header-desktop" %>
<%= render "header-phone" %>
<main class="mdl-grid landing-container__desktop">
  <%= render "hero-message-desktop" %>
  <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-phone">
    <%= image_tag "ilustra-landing.svg", { id: "main-illustration" } %>
  </div>
  <%= render "hero-message-phone" %>
  <%= render "features" %>
  <%= render "price" %>
  <%= render "form" %>
</main>
<%= render 'shared/footer' %>