config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'landing/index'
  root to: 'landing#index'

  match '/auth/:provider/callback',           to: 'sessions#create', via: [:get, :post]
  get   '/login',                             to: 'sessions#new'
  get   '/auth/failure',                      to: 'sessions#failure'
  match '/logout',                            to: 'sessions#destroy', via: [:get, :post]
  get   '/signup',                            to: 'identities#new' # registering user with omniauth-identity
  get   '/home',                              to: 'homes#index'
  post  '/contact/submit',                    to: 'forms#submit_contact'
  put   '/account/choose',                    to: 'accounts#choose'
  get   '/plans',                             to: 'application#plans_route'

  resources :accounts
  resources :identities
  resources :statements                     
  resources :users,                           only: [:show]
  resources :statement_files,                 only: [:index, :new, :create, :destroy]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount Sidekiq::Web, at: '/sidekiq' if Rails.env.development?
end
 

app/views/shared/_footer.html.erb
<footer class="mdl-mini-footer footer ">
  <div class="mdl-mini-footer__left-section">
    <div class="mdl-logo">
      <img src="/assets/logo.svg" width="90">
    </div>
    <ul class="mdl-mini-footer__link-list">
      <li><a href="#">Página Inicial</a></li>
      <li><a href="#">Ajuda</a></li>
      <li><a href="#">Termos de Privacidade</a></li>
    </ul>
  </div>
  <div class="mdl-mini-footer__right-section">
    <li><a href="#">&copy; Todos os direitos reservados.</a></li>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header class="mdl-layout__header header">
  <div class="mdl-layout__header-row">
    <div class="mdl-layout-spacer">
    <%= form_tag account_choose_path, :method => 'put' do %>
    <%= select_tag 'choosen_account_id', 
      options_from_collection_for_select(current_user.accounts, 'id', 'name', 
        selected: choosen_account&.id), 
        prompt: 'Escolha a conta', 
        onchange: 'this.form.submit();', 
        class: 'mdl-button mdl-js-button account-btn' %>
    <% end %>
    </div>
    <nav class="mdl-navigation">
      <span class="material-icons mr-10 nav-item">
        <%= link_to "account_circle", user_path(current_user.id) %>
      </span>
      <span class="material-icons nav-item">
        <%= link_to "settings", "" %>
      </span>
      <div id="demo-menu-lower-right" class="mdl-button mdl-js-button mdl-button--icon">
        <i class="material-icons nav-item">more_vert</i>
      </div>
      <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu nav-menu mdl-js-ripple-effect" for="demo-menu-lower-right">
        <li class="mdl-menu__item">
          <%= link_to "Página Inicial", home_path %>
        </li>
        <li class="mdl-menu__item">
          <%= link_to "Perfil", user_path(current_user.id) %>
        </li>
        <li class="mdl-menu__item">
          <%= link_to "Listas de Notas de Corretagem", statement_files_path %>
        </li>
        <li class="mdl-menu__item">
          <%= link_to "Adicionar Notas de Corretagem", new_statement_file_path %>
        </li>
        <li class="mdl-menu__item">
          <%= link_to "Lista de Contas de Usuário", accounts_path %>
        </li>
        <li class="mdl-menu__item">
          <%= link_to "Adicionar Contas de Usuário", new_account_path %>
        </li>
        <li class="mdl-menu__item">
          <%= link_to "Logout", logout_path %>
        </li>
      </ul>
    </nav>
  </div>
</header>