config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'landing/index'
  root to: 'landing#index'

  match '/auth/:provider/callback',           to: 'sessions#create', via: [:get, :post]
  get   '/login',                             to: 'sessions#new'
  get   '/auth/failure',                      to: 'sessions#failure'
  match '/logout',                            to: 'sessions#destroy', via: [:get, :post]
  get   '/signup',                            to: 'identities#new' # registering user with omniauth-identity
  get   '/home',                              to: 'homes#index'
  post  '/contact/submit',                    to: 'forms#submit_contact'
  put   '/account/choose',                    to: 'accounts#choose'
  get   '/plans',                             to: 'application#plans_route'

  resources :accounts
  resources :identities
  resources :statements                     
  resources :users,                           only: [:show]
  resources :statement_files,                 only: [:index, :new, :create, :destroy]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount Sidekiq::Web, at: '/sidekiq' if Rails.env.development?
end
 

app/models/statement.rb
class Statement < ApplicationRecord
  belongs_to :statement_file, optional: true
  belongs_to :brokerage_account

  has_many :trades, dependent: :destroy

  before_validation :set_brokerage_account_from_content
  before_validation :set_statement_date_from_content
  # after_create :generate_trades
  # after_create :set_costs
  # after_create :set_paid_taxes

  validates :number, uniqueness: { scope: :brokerage_account_id }
  validates :statement_date, presence: true
  validates :number, presence: true

  accepts_nested_attributes_for :trades, allow_destroy: true, reject_if: :all_blank

  private

    def set_statement_date_from_content
      if content && statement_file
        self.statement_date = content.match('\d{1,2}\/\d{1,2}\/\d{4}').to_s
      end
    end

    def set_brokerage_account_from_content
      if content && statement_file
        client_number = content.match('\d{7}\-?\d{1}').to_s
        account = statement_file.account
        self.brokerage_account = account.brokerage_accounts.find_or_create_by(brokerage: 1, number: client_number)
      end
    end

    def parser
      @parser ||= StatementParser.new(content: content) if content
    end

    def generate_trades
      if content
        parser.trades.each do |trade|
          trades.create(trade)
        end
      end
    end

    def set_costs
      if content
        # TODO: Set the costs related to this statement from the parser data
      end
    end

    def set_paid_taxes
      if content
        # TODO: Set the paid taxes related to this statement from the parser data
      end
    end
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :set_statement,             only: [:edit, :update, :show, :destroy]
  before_action :set_last_account,          only: [:index, :create, :new]

  def index
    @pagy, @statements = pagy(Statement.where(brokerage_account: choosen_account.brokerage_accounts), items: 10)
  end

  def show
  end

  def new
    @statement = Statement.new
  end

  def edit
  end

  def create
    begin
      @statement = choosen_account.brokerage_accounts.find_or_create_by(brokerage: 1, number: '123456-7').statements.build(statement_params)
            
      if @statement.save
        redirect_to statements_path, notice: t('.notice')
      else
        redirect_to new_statement_path, alert: @statement.errors.full_messages.to_sentence
      end
    rescue ActionController::ParameterMissing => exception
      redirect_to new_statement_path
    end
  end

  def update
    if @statement.update(statement_params)
      flash[:notice]  = t('.notice')
    else
      flash[:alert] = @statement.errors.full_messages.to_sentence
    end
    redirect_back(fallback_location: statements_path)
  end

  def destroy
    if @statement.destroy
      redirect_to statements_path, notice: t('.notice')
    else
      redirect_to statements_path, alert: t('.alert')
    end
  end

  private

    def set_statement
      @statement = Statement.find(params[:id])
      @pagy, @trades = pagy(Trade.where(statement_id: params[:id]), items: 10)
    end

    def statement_params
      params.require(:statement).permit(:content, :statement_date, :number, trades_attributes: [
        :id, :ticker, :direction, 
        :open, :close, 
        :quantity, :price, 
        :transacted_at, :_destroy])
    end
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/statements/_empty.html.erb
<tr class="main-content" style="visibility: collapse;">
  <td>
    <%= text_field :ticker, class: 'mdl-textfield__input ', type: 'text' %>
  </td>
  <td>
    <%= radio_button :direction, 0, class: 'mdl-checkbox__input', type:'checkbox' %>
    <%= radio_button :direction, 1, class: 'mdl-checkbox__input', type:'checkbox' %>
  </td>
  <td>
    <%= text_field :quantity, class: 'mdl-textfield__input', type: 'number' %>
  </td>
  <td>
    <%= text_field :price, step: :any, class: 'mdl-textfield__input', type: 'number' %>
  </td>
  <td></td>
</tr>

app/views/statements/_form.html.erb
<div>
  <fieldset>
    <%= form_with(model: statement, local: true) do |form| %>
      <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
        <%= form.date_field :statement_date, class: 'mdl-textfield__input', id:'date-input', style: "color: black;" %>
      </div>
      <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
        <%= form.label 'Número', class: 'mdl-textfield__label', for: 'number' %>
        <%= form.text_field :number, class: 'mdl-textfield__input', type: 'number', maxlength: '15' %>
      </div>
      <div class="nested-fields-wrapper">
        <div class="buttons-group">
          <%= link_to_add_fields "Adicionar negociação", form, :trades, class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored ma-10' %>
          <div class="actions">
            <%= form.submit 'Salvar', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored ma-10' %>
          </div>
        </div>
        <span>
          <p class="ma-10" style="color: rgb(103,58,183);">É necessário clicar em <strong>'SALVAR'</strong> para as alterações serem feitas!</p>
        </span>
        <h5 class="mdl-typography--headline ma-10">
          Negociações
        </h5>
        <table class="mdl-data-table mdl-js-data-table statements-table ma-10 mdl-shadow--2dp">
          <thead>
            <tr>
              <th>Ativo</th>
              <th>Compra/Venda</th>
              <th>Quantidade</th>
              <th>Preço Unit.</th>
              <th id="status_title"> Aberta/Fechada
                <div class="mdl-tooltip mdl-tooltip--large" for="status_title">
                  Status da Negociação
                </div>
              </th>
              <th></th>
            </tr>
          </thead>
          <tbody class="nested-container">
            <%= render 'empty' %>
            <% if @trades %>
              <%= form.fields_for :trades, @trades.order(id: :desc) do |trade_form| %>
                <%= render 'trade_fields', f: trade_form %>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <div class="ma-10"><%== pagy_nav(@pagy) if @pagy.pages > 1 unless !@trades %></div>
        <div class="mt-40">
          <h5 class="mdl-typography--headline ma-10">
            Taxas e Impostos
          </h5>
          <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
            <%= form.label 'Taxa de Liquidação', class: 'mdl-textfield__label', for: 'liquidation_fee' %>
            <%= form.number_field :liquidation_fee, step: :any, min: 0, class: 'mdl-textfield__input' %>
          </div>
          <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
            <%= form.label 'Taxa de Registro', class: 'mdl-textfield__label', for: 'registration_fee' %>
            <%= form.number_field :registration_fee, step: :any, min: 0, class: 'mdl-textfield__input', type: 'decimal', maxlength: '15' %>
          </div>
          <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
            <%= form.label 'Taxa de Termos/Opções', class: 'mdl-textfield__label', for: 'terms_fee' %>
            <%= form.number_field :terms_fee, step: :any, min: 0, class: 'mdl-textfield__input', type: 'decimal', maxlength: '15' %>
          </div>
          <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
            <%= form.label "Taxa ANA", class: 'mdl-textfield__label', for: 'ana_fee' %>
            <%= form.number_field :ana_fee, step: :any, min: 0, class: 'mdl-textfield__input', type: 'decimal', maxlength: '15' %>
          </div>
          <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
            <%= form.label 'Emolumentos', class: 'mdl-textfield__label', for: 'exchange_fee' %>
            <%= form.number_field :exchange_fee, step: :any, min: 0, class: 'mdl-textfield__input', type: 'decimal', maxlength: '15' %>
          </div>
          <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
            <%= form.label 'Taxa Operacional', class: 'mdl-textfield__label', for: 'operational_fee' %>
            <%= form.number_field :operational_fee, step: :any, min: 0, class: 'mdl-textfield__input', type: 'decimal', maxlength: '15' %>
          </div>
          <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
            <%= form.label 'Execução', class: 'mdl-textfield__label', for: 'execution_fee' %>
            <%= form.number_field :execution_fee, step: :any, min: 0, class: 'mdl-textfield__input', type: 'decimal', maxlength: '15' %>
          </div>
          <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
            <%= form.label 'Taxa de Custódia', class: 'mdl-textfield__label', for: 'custody_fee' %>
            <%= form.number_field :custody_fee, step: :any, min: 0, class: 'mdl-textfield__input', type: 'decimal', maxlength: '15' %>
          </div>
          <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
            <%= form.label 'Impostos', class: 'mdl-textfield__label', for: 'taxes' %>
            <%= form.number_field :taxes, step: :any, min: 0, class: 'mdl-textfield__input', type: 'decimal', maxlength: '15' %>
          </div>
          <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
            <%= form.label 'IRRF', class: 'mdl-textfield__label', for: 'capital_gain_tax' %>
            <%= form.number_field :capital_gain_tax, step: :any, min: 0, class: 'mdl-textfield__input', type: 'decimal', maxlength: '15' %>
          </div>
          <div class="mdl-textfield mdl-js-textfield statement-field field ma-10 mdl-textfield--floating-label">
            <%= form.label 'Outros', class: 'mdl-textfield__label', for: 'other_fees' %>
            <%= form.number_field :other_fees, step: :any, min: 0, class: 'mdl-textfield__input', maxlength: '15' %>
          </div>
        </div>    
        <div class="mdl-button mdl-js-button add-file trade-btn ma-10">
          <span class="material-icons trade-icon">
            <%= link_to 'arrow_back', statements_path %>
          </span>
        </div>
      </div>
    <% end %>
  </fieldset>
</div>

app/views/statements/_trade_fields.html.erb
<tr class="nested-fields">
  <fieldset>
    <td>
      <%= f.text_field :ticker, class: 'mdl-textfield__input', type: 'text', style:"text-align: center;" %>
    </td>
    <td>
      <%= f.radio_button :direction, 0, class: 'mdl-checkbox__input' %>
      <%= f.radio_button :direction, 1, class: 'mdl-checkbox__input' %>
    </td>
    <td>
      <%= f.number_field :quantity, min: 1, class: 'mdl-textfield__input', style:"text-align: center;" %>
    </td>
    <td>
      <%= f.number_field :price, step: :any, min: 0, class: 'mdl-textfield__input', style:"text-align: center;" %>
    </td>
    <td>
      <%= f.radio_button :status, "open", class: 'mdl-checkbox__input' %>
      <%= f.radio_button :status, "close", class: 'mdl-checkbox__input' %>
    </td>
    <td>
      <%= f.hidden_field :_destroy %>
      <div class="mdl-button mdl-js-button mdl-button--icon table-button">
        <i class="material-icons table-item"><%= link_to "delete", '#', class: "remove_fields" %></i>
      </div>
    </td>
  </fieldset>
</tr>

app/views/statements/edit.html.erb
<div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-phone main-content ma-40">
  <h1 class="mdl-typography--display-1 ma-10">
    <h5 class="mdl-typography--headline ma-10">
      Dados da Nota de Corretagem
    </h5>
  </h1>
  <%= render 'form', statement: @statement, trades: @trades, pagy: @pagy %>
</div>

app/views/statements/index.html.erb
<div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-phone main-content ma-40">
  <h1 class="mdl-typography--display-1 ma-10">Listagem das Notas de Corretagem</h1>
  <div class="mdl-button mdl-js-button add-file ma-10 mdl-button--raised mdl-button--colored">
    <%= link_to 'Nova Nota de Corretagem', new_statement_path %>
  </div>
  <table class="mdl-data-table mdl-js-data-table ma-10 mdl-shadow--2dp">
    <thead>
      <tr>
        <th class="mdl-data-table__cell--non-numeric" id="column-date">Data</th>
        <th>Número</th>
        <th>Arquivo Anexo</th>
        <th>Corretora</th>
        <th>Nota de Corretagem</th>
      </tr>
    </thead>
    <tbody>
      <% @statements.each do |statement| %>
        <tr>
          <td class="mdl-data-table__cell--non-numeric"><%= statement.statement_date.to_date %>
          <td><%= statement.number %></td>
          <% if statement.statement_file %>
            <td><%= link_to 'visualizar anexo', statement.statement_file.file, target: '_blank', class:'preview-file' %></td>
          <% else %>
            <td>sem anexo</td>
          <% end %>
          <td><%= statement.brokerage_account_id %></td>
          <td>
            <div class="mdl-button mdl-js-button mdl-button--icon table-button">
              <i class="material-icons table-item"><%= link_to 'visibility', statement %></i>
            </div>
            <div class="mdl-button mdl-js-button mdl-button--icon table-button">
              <i class="material-icons table-item"><%= link_to 'edit', edit_statement_path(statement) %></i>
            </div>
            <div class="mdl-button mdl-js-button mdl-button--icon table-button">
              <i class="material-icons table-item"><%= link_to 'delete', statement, method: :delete, data: { confirm: 'Você tem certeza?' } %></i>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <div class="ma-10"><%== pagy_nav(@pagy) if @pagy.pages > 1 %></div>
</div>

app/views/statements/new.html.erb
<div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-phone main-content ma-40">
  <h1 class="mdl-typography--display-1 ma-10">
    Nota de Corretagem
  </h1>
  <%= render 'form', statement: @statement %>
</div>

app/views/statements/show.html.erb
<div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-phone main-content ma-40">
  <h5 class="mdl-typography--headline ma-10">
    Dados da Nota de Corretagem
  </h5>
  <%= render 'form', statement: @statement, trades: @trades, pagy: @pagy %>
</div>