config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'landing/index'
  root to: 'landing#index'

  match '/auth/:provider/callback',           to: 'sessions#create', via: [:get, :post]
  get   '/login',                             to: 'sessions#new'
  get   '/auth/failure',                      to: 'sessions#failure'
  match '/logout',                            to: 'sessions#destroy', via: [:get, :post]
  get   '/signup',                            to: 'identities#new' # registering user with omniauth-identity
  get   '/home',                              to: 'homes#index'
  post  '/contact/submit',                    to: 'forms#submit_contact'
  put   '/account/choose',                    to: 'accounts#choose'
  get   '/plans',                             to: 'application#plans_route'

  resources :accounts
  resources :identities
  resources :statements                     
  resources :users,                           only: [:show]
  resources :statement_files,                 only: [:index, :new, :create, :destroy]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount Sidekiq::Web, at: '/sidekiq' if Rails.env.development?
end
 

app/models/statement_file.rb
class StatementFile < ApplicationRecord
  has_one_attached :file
  has_many :statements, dependent: :destroy
  belongs_to :account
  after_create :parse_file

  validates :account, presence: true
  validates :file, presence: true
  validates :file, attached: true,
    size: { less_than: 20.megabytes },
    content_type: { in: 'application/pdf' }

  private
    def parse_file
      ProcessStatementFileJob.perform_later(statement_file_id: id)
    end
end

app/controllers/statement_files_controller.rb
class StatementFilesController < ApplicationController
  before_action :set_statement_file,        only: [:destroy]
  before_action :set_last_account,          only: [:index, :create, :new]

  def index
    @statement_files = StatementFile.all
  end

  def new
    @statement_file = StatementFile.new
  end

  def create
    begin
      @statement_file = choosen_account.statement_files.build(statement_file_params)

      if @statement_file.save
        redirect_to statement_files_path, notice: t('.notice')
      else
        redirect_to statement_files_path, alert: t('.alert')
      end
    rescue ActionController::ParameterMissing => exception
      redirect_to statement_files_path, alert: t('.alert')
    end
  end

  def destroy
    if @statement_file.destroy
      redirect_to statement_files_path, notice: t('.notice')
    else
      redirect_to statement_files_path, alert: t('.alert')
    end
  end

  private

  def set_statement_file
    @statement_file = StatementFile.find(params[:id])
  end

  def statement_file_params
    params.require(:statement_file).permit(:file)
  end
end

app/helpers/statement_files_helper.rb
module StatementFilesHelper
end

app/views/statement_files/_form.html.erb
<%= form_with model: StatementFile, method: :post, local: true do |f| %>
  <%= f.file_field :attach_file, accept: '.pdf' %><br /><br />
  <%= f.submit 'Upload' %>
<% end %>
<br>
<br>
<br>
<%= link_to "Logout", "/logout" %>

app/views/statement_files/edit.html.erb
<h1>Editing Statement File</h1>

<%= render 'form', statement_file: @statement_file %>

<%= link_to 'Show', @statement_file %> |
<%= link_to 'Back', statement_files_path %>

app/views/statement_files/index.html.erb
  <div class="root-container">
    <div class="mdl-cell mdl-cell--8-col mdl-cell--4-col-phone main-content ma-40">
      <div class="content">
        <h1 class="mdl-typography--display-1 ma-10">
          Notas de Corretagem Importadas
        </h1>
        <div class="mdl-button mdl-js-button add-file ma-10 mdl-button--raised mdl-button--colored">
        <%= link_to 'Adicionar Arquivo', new_statement_file_path %>
        </div>
        <table class="mdl-data-table mdl-js-data-table ma-10 mdl-data-table--selectable mdl-shadow--2dp">
          <thead>
            <tr>
              <th class="mdl-data-table__cell--non-numeric">Id</th>
              <th class="date">Data de criação</th>
              <th>Nota de Corretagem</th>
            </tr>
          </thead>
          <tbody>
            <% @statement_files.each do |statement_file| %>
            <tr>
              <td class="mdl-data-table__cell--non-numeric"><%= statement_file.file.record.id %></td>
              <td class="date-data"><%= statement_file.file.record.created_at.to_date %></td>
              <td>
                <div class="mdl-button mdl-js-button mdl-button--icon table-button">
                  <i class="material-icons table-item"><%= link_to 'visibility', statement_file.file, target: '_blank'%></i>
                </div>
                <div class="mdl-button mdl-js-button mdl-button--icon table-button">
                  <i class="material-icons table-item"><%= link_to 'get_app', statement_file.file, download: ''%></i>
                </div>
                <div class="mdl-button mdl-js-button mdl-button--icon table-button">
                  <i class="material-icons table-item"><%= link_to 'delete', statement_file, method: :delete, id: statement_file, data: { confirm: 'Tem certeza que deseja excluir esse arquivo?' } %></i>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/statement_files/new.html.erb
  <div class="root-container"> 
    <div class="mdl-cell mdl-cell--6-col ma-40">
      <div class="content">
        <div class="mdl-layout__content">
          <h1 class="mdl-typography--display-1 ma-10">
            Adicionar Notas de Corretagem
          </h1>
          <%= form_with model: StatementFile, method: :post, local: true do |f| %>
              <div class="button-group">
                <div class="content-group">
                  <%= f.file_field :file, id: 'file', class: 'hidden', accept: '.pdf' %>
                  <%= f.submit 'Anexar arquivo', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored ma-10' %>
                  <label class="mdl-typography--body-1 ma-20" for="file">Escolha o arquivo</label>
                </div>
                <%= link_to 'Voltar', statement_files_path, class: 'ma-10 purple-btn mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/statement_files/show.html.erb
<p>
  <strong>Statment File:</strong>
  <%= @statement_file.attach_file %>
</p>

<%= link_to 'Edit', edit_statement_file_path(@statement_file) %> |
<%= link_to 'Back', statement_files_path %>